name: :rocket: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]

body:
  - type: dropdown
    attributes:
      label: Which django app(s) are relevant/releated to the feature request?
      options:
        - Auth

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Answer this questions:
        - Why is this change important to you?
        - How would you use it?
        - How can it benefit other users?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
